const mongoose = require('mongoose');

const tripSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    destination: {
      type: String,
      required: true,
      trim: true,
    },
    startDate: {
      type: Date,
      required: true,
    },
    endDate: {
      type: Date,
      required: true,
    },
    budget: {
      type: String,
      required: true,
      enum: ['Budget', 'Moderate', 'Luxury'],
      default: 'Moderate',
    },
    travelers: {
      type: Number,
      required: true,
      default: 1,
      min: 1,
    },
    // This field will store the complex, nested JSON data generated by the Gemini AI
    itineraryData: {
      type: mongoose.Schema.Types.Mixed,
      required: true,
    }
  },
  { timestamps: true }
);

module.exports = mongoose.model('Trip', tripSchema);